#!/bin/bash
# inpath -- Verifies that a specified program is either valid as is or can be found in the PATH directory list

in_path() {
  # Given a command and the PATH, tries to find the command.  Returns 0 if found and executable, 1 if not.
  # NOTE: This temporarily modifies the IFS (internal field separator) but restores it upon completion.

  
}